Add env configuration
samvyatkin/shortener pull request #5
Opened 2024-07-25 20:33 UTC by samvyatkin

2024-07-31 22:25 UTC, avhitrov requested changes
Архитектурно все грамотно, есть замечания, отмечены в комментариях к коду.

2024-07-31 22:25 UTC, avhitrov commented on cmd/shortener/main.go
> +	return http.ListenAndServe(c.ServerAddr(), r)
```suggestion
	log.Fatal(http.ListenAndServe(c.ServerAddr(), r))
```
Так принято - в случае ошибки выводится сама ошибка и программа падает с os.Exit(1). Если ошибки нет - log.Fatal не срабатывает.

2024-07-31 22:25 UTC, avhitrov commented on internal/app/handlers/create/handler.go
> +	defer req.Body.Close()
Данный defer должен находиться после проверки ошибки от io.ReadAll. Может так случиться, что req.Body будет равен nil, и тогда defer от Close() выдаст панику.

https://t.me/bushigo/21

2024-07-31 22:25 UTC, avhitrov commented on internal/app/handlers/search/handler.go
> +	}
Это не go-стиль и здесь повышенная цикломатическая вложенность. Go-стиль - это повсеместно проверять возвращаемые ошибки и возможные исключения - и сразу их обрабатывать. В данном случае
1. Проверить, что `u == nil`, и если да - то сформировать BadRequest и завершить функцию по return.
2. Ошибки проверяются не на равен `err == nil`, а на `err != nil`, после чего идет реакция и экстренный выход. Иначе заплутаем во всевозможных else.

2024-07-31 22:25 UTC, avhitrov commented on internal/app/storage/in_memory.go
> +	cache map[string]string
Мапа – структура потоконебезопасная. Это означает, что в конкурентной среде (а http-сервер априори является конкурентным приложением, так как открывает по горутине на каждый входящий запрос) любые обращения к ней должны оборачиваться блокировками. В Go для этого существуют мьютексы (sync.Mutex или sync.RWMutex). Кроме того, можно использовать потокозащищенные структуры, вроде sync.Map.

Подробнее: https://t.me/bushigo/24

В данном же случае при множестве одновременных запросов имеем:
```
==================
WARNING: DATA RACE
Write at 0x00c0000990b0 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/runtime/map_faststr.go:203 +0x0
  shortener/internal/app/storage.(*InMemoryStorage).Set()
      C:/work/src/github.com/samvyatkin/shortener/internal/app/storage/in_memory.go:14 +0x64
  shortener/internal/app/handlers/create.(*Handler).Handle()
      C:/work/src/github.com/samvyatkin/shortener/internal/app/handlers/create/handler.go:45 +0x2ed
  shortener/internal/app/handlers/create.(*Handler).Handle-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  main.run.Timeout.func2.1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/timeout.go:44 +0x17d
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.RequestID.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/request_id.go:76 +0x30b
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.Recoverer.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/recoverer.go:45 +0xf0
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.RealIP.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/realip.go:36 +0xcc
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:55 +0x253
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x69e
  net/http.serverHandler.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:3285 +0x4f

Previous read at 0x00c0000990b0 by goroutine 40:
  runtime.mapaccess2_faststr()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/runtime/map_faststr.go:108 +0x0
  shortener/internal/app/storage.(*InMemoryStorage).Get()
      C:/work/src/github.com/samvyatkin/shortener/internal/app/storage/in_memory.go:18 +0x54
  shortener/internal/app/handlers/search.(*Handler).Handle()
      C:/work/src/github.com/samvyatkin/shortener/internal/app/handlers/search/handler.go:24 +0x15b
  shortener/internal/app/handlers/search.(*Handler).Handle-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:73 +0x716
  github.com/go-chi/chi/v5.(*Mux).Mount.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:327 +0x4e5
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5.(*Mux).routeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x594
  github.com/go-chi/chi/v5.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  main.run.Timeout.func2.1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/timeout.go:44 +0x17d
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.RequestID.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/request_id.go:76 +0x30b
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.Recoverer.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/recoverer.go:45 +0xf0
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.RealIP.func1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/realip.go:36 +0xcc
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.windows-amd64/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi/v5/middleware.init.0.RequestLogger.func1.1()
      C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/logger.go:55 +0x253
  net/http.HandlerFunc.ServeHTTP()
      C:/Users/Khitrov_An/go/pkg [...]

2024-08-04 14:12 UTC, samvyatkin commented on cmd/shortener/main.go
> +	return http.ListenAndServe(c.ServerAddr(), r)
Исправлено ✅

2024-08-04 14:12 UTC, samvyatkin commented on internal/app/handlers/create/handler.go
> +	defer req.Body.Close()
Исправлено ✅

2024-08-04 14:12 UTC, samvyatkin commented on internal/app/handlers/search/handler.go
> +	}
Исправлено ✅

2024-08-04 14:12 UTC, samvyatkin commented on internal/app/storage/in_memory.go
> +	cache map[string]string
Исправлено ✅

2024-08-08 15:20 UTC, avhitrov approved these changes
Все замечания обработаны. Отлично!

2024-08-08 16:27 UTC, merged