Add file storage
samvyatkin/shortener pull request #9
Opened 2024-08-31 21:14 UTC by samvyatkin

2024-09-02 21:33 UTC, avhitrov requested changes
Структура единого интерфейса для обоих хранилищ - решение правильное, но не докрученное до конца. Необходимо организовать замещение одного хранилища другим в зависимости от набора переданных параметров. В настоящий момент при запуске с ключом `-f=""` сервер просто падает. А должен работать, как раньше - с хранением только в памяти.

Подробности в комментариях.

2024-09-02 21:33 UTC, avhitrov commented on cmd/shortener/main.go
> +func Load(path string) ([]models.ShortenData, error) {
```
if path == "" {
    return nil, nil
}
```
Ситуация, когда файловое хранилище отключено (запуск с ключом `-f=""`) - штатная и предусмотрена ТЗ. В этом случае вместо файлового хранилища должно быть задействовано in-memory, все файловые операции отменяются.

2024-09-02 21:33 UTC, avhitrov commented on internal/app/handlers/shorten/handler.go
> +	}
Не совсем верная реализация.
1. Если имя файла указано пустым значением, то хендлер будет всегда падать при попытке записать данные.
2. Файловое хранилище должно замещать in-memory хранилище. То есть в один момент времени в зависимости от набора переданных переменных хендлер должен работать только с одним инициализированным хранилищем. В следующих итерациях хранилища станет три (добавится БД) и код может радикально усложниться.

В принципе, на уровне интерфейса хранилища все сделано правильно - он един и для памяти, и для файлов. Но необходимо дописать функцию Get у файлового хранилища так, чтобы она полноценно доставала данные. Либо из файла, либо из памяти (в этом случае in-memory включается в состав файлового и работает, как кеш). Кроме того, в функции main необходимо дописать выбор, а в хендлер складывать один единственный storage.

2024-09-02 21:33 UTC, avhitrov commented on internal/app/handlers/shorten/handler.go
> +	fileStorage     storage.Storage
```suggestion
	Storage storage.Storage
```

2024-09-13 20:31 UTC, samvyatkin commented on cmd/shortener/main.go
> +func Load(path string) ([]models.ShortenData, error) {
Исправил ✅

2024-09-13 20:31 UTC, samvyatkin commented on internal/app/handlers/shorten/handler.go
> +	}
Исправил ✅

2024-09-13 20:31 UTC, samvyatkin commented on internal/app/handlers/shorten/handler.go
> +	fileStorage     storage.Storage
Исправил ✅

2024-09-19 18:09 UTC, avhitrov approved these changes
Все замечания исправлены, хороший рефакторинг. Ставлю аппрув, но рекомендую немного покрутить сервис - хендлер, выставляющий 307 редирект, также выдает заголовок `Content-Length: 26`, на деле не выдавая тело ответа. curl и go-шный getter ругаются на подобный ответ.

2024-09-19 20:35 UTC, merged